### PR TITLE
Chisq Binary test 

### PR DESCRIPTION
**Pull request by Gakehoe**
@jjuvan could you test out the new version i have made? these changes that i have made include those that you have suggested. @rkehoe could you check out the edits i have made.

### CODE REVIEW

**Comment by Gakehoe** [comment]
This is the pull request for Chisq Binary test which was developed to help differentiate between wether a light curve is a binary or pulsating star. The package uses a series of math and the chisq equation to tell wether the two minima in the light curve are similar or different. Some of the changes made further in this package was suggested by @jjuvan in the issue #35

**Comment by rkehoe** [comment]
@Gakehoe Code looks like it is coming along.  I would go ahead and now remove the commented out lines for imports and methods you are no longer using.  Please also move the 1 line comments describing each method to appear right after the ‘def’ line at their tops, and please leave a blank line between ‘return’ of one method and ‘def’ of another.  After this bit of cleanup, please test and commit that.  I would then ask that you consolidate your arguments for the fit parameters into one argument ‘fitpars’, so that your top-level methods in ‘main’ are less unwieldy for the user.  After that, I also encourage you to include an ‘args’ functionality so the user can specify inputs like filename.  There will be others to set also, but we can deal with that after the above edits are in place.

**Comment by Gakehoe** [comment]
@rkehoe i have made changes that you have suggested and have pushed the changes.

**Comment by Gakehoe** [comment]
@jjuvan could you try it again? I have made some changes to the code that i realized were not part of it that were causing the code a problem. It may still not work but could you still try it again and see if it works.

**Comment by jjuvan** [comment]
@Gakehoe Can you send me the file of the object that you used so that I can run the code? I also need to make sure that the previous iteration of the code has the same output as the current one for the same object.

**Comment by jjuvan** [comment]
@Gakehoe @rkehoe I have successfully ran the program on the object Aidan has been using (J1125+4234 old lcvis file, two points per observation spaced one phase apart). Below is the output I received. I am going to try running the program on the same object using the new lcvis file and report with a new comment shortly.

**Comment by jjuvan** [comment]
@Gakehoe @rkehoe I ran the program on the same object, this time with the new lcvis file and one with the original file but sorted on phase. The first image shows the error that I get when running the Chisq program on the new lcvis file (only one point per observation, phases between 0 and 1), and the second shows the new and different output I get with the old lcvis file, but sorted.

image
Output with new lcvis file

image
Output with old lcvis file, sorted on phase

**Comment by jjuvan** [comment]
This is the error I get when running the code on a different object (new lcvis file)
Screenshot 2024-07-26 at 12 11 42 AM
image

**Comment by Gakehoe** [comment]
@jjuvan could you test the code again? I fixed the code so that it should run with the new lcvis file. You may still run into a problems due to paramenters.

**Comment by jjuvan** [comment]
@Gakehoe I ran the code again, this time on the new lcvis file that I sent you. Let me know if you get the same result I do.
image

**Comment by rkehoe** [comment]
@Gakehoe Are those #s consistent with what you get for the same variable?  I’m guessing that one file is sorted, and the other is not?  It would be useful to take Jacob’s file-from-lcvis and yours where you filtered out the phase 1-2 data, and compare the fit parameters and final chi squareds.  It may be that the sorting causes different data points to end up in your truncated  lists of measurements for each minimum that you extract from sorted_lc.

**Comment by rkehoe** [comment]
@Gakehoe @jjuvan Can we also try this on another eclipsing star, like an EW, to see the chi-squareds of the two minima are more similar?  Also, to verify the code can run on another object.  There will be work to tune the algorithm and operating parameters (eg. Window widths around minima, # of data points per minimum to extract, etc.], so we may need to punt that to the next branch and merge this one, but a quick check with one or two other stars would help.  @jjuvan I think it’s easier for you to make some files from lcvis since your re analyzing EWs right now.  Could you provide those to @gakehoe and also run them yourself thru chisq_binarytest?

**Comment by Gakehoe** [comment]
Hey @jjuvan @rkehoe i have run all of the lcvis.dat files only two of them worked(one from the ursas and the other beta-lyrae) but they both had a terrible output(the output was all in the negative) for the rest they all were not able to run fully and ran into number of indexes range problems.

**Comment by Gakehoe** [comment]
@jjuvan @rkehoe This is the output i get for the w-ursa-majoris 
Screenshot 2024-08-17 at 1 18 07 PM
It is similar to what i get for the beta lyrae
beta-lyrae
Then for the rest they run into different problems The two problems look like this 
Screenshot 2024-08-17 at 1 13 43 PM
Screenshot 2024-08-17 at 1 18 54 PM

**Comment by rkehoe** [comment]
Okay, thanks @Gakehoe and @jjuvan .  It looks like there is a) something off with the chi-squared calculation, and b) something problematic in the first minimum finder that is crashing.  You indicated a 2nd type of crash, but did not show the error message in your screenshot.  Well want to see that in the Issue I suggest you create (see below).  Still, the two objects you provided that did fit seems to identify statistically significant minima in both cases.  Plus it does run on two further objects.  My guess is the crashes are due to the hardcoded parameters that are still in the algorithm.  

Normally, I would not merge this and let further development ensue, but I think this level accomplishes the first goals we had and it allows @jjuvan to start considering how to integrate this into lcvis.  For these reasons, I will merge this PR into master.  @Gakehoe I ask that you prepare a new Issue with your final screenshots, including the error message for the 2nd type of crash that you omitted.  This will be the basis of a new line of development that can tackle the negative chi squareds and the crashes and hardcoded parameters.  We can discuss that in September when we resume our Saturday meetings.

**Pull request merged**
